name: Actions

on: [push, pull_request, workflow_dispatch]

jobs:
  run_test:
    name: Run Tests

    permissions:
      checks: write

    strategy:
      matrix:
        unityVersion:
          - 6000.0.32f1
          - 2023.2.20f1
          - 2022.3.55f1
        os:
          - ubuntu-latest
          # - windows-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Test
      - name: run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          packageMode: true
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}